---

- name: "{{ crc_mode }} | crc | download and install Code Ready Container with checksum control"
  become: true
  when: not ansible_check_mode
  ansible.builtin.get_url:
    url: "{{ crc_download_url }}"
    dest: "{{ crc_tmp_dir }}/{{ crc_download_file_name }}"
    mode: "0755"
    owner: root
    group: root
    checksum: "{{ crc_download_url_checksum }}"

- name: "{{ crc_mode }} | crc | unarchive"
  become: true
  when: not ansible_check_mode
  ansible.builtin.unarchive:
    src: "{{ crc_tmp_dir }}/{{ crc_download_file_name }}"
    dest: "{{ crc_tmp_dir }}"
    remote_src: yes

- name: "{{ crc_mode }} | crc | put binary in /usr/local/bin"
  become: true
  when: not ansible_check_mode
  ansible.builtin.copy:
    src: "{{ crc_tmp_dir }}/{{ crc_download_folder_name }}/crc"
    dest: /usr/local/bin
    remote_src: true
    mode: '0755'

- name: "{{ crc_mode }} | crc | check installed"
  become: true
  ansible.builtin.command: crc version
  register: __crc_install_status
  changed_when: __crc_install_status.rc != 2

- name: "{{ crc_mode }} | crc | ocp and kubectl | download and install Openshift Client and Kubernetes Client with checksum control"
  become: true
  when: not ansible_check_mode
  ansible.builtin.get_url:
    url: "{{ crc_ocp_download_url }}"
    dest: "{{ crc_tmp_dir }}/{{ crc_ocp_download_file_name }}"
    mode: "0755"
    owner: root
    group: root
    checksum: "{{ crc_ocp_download_url_checksum }}"

- name: "{{ crc_mode }} | crc | ocp and kubectl | unarchive and put it in /usr/local/bin"
  become: true
  when: not ansible_check_mode
  ansible.builtin.unarchive:
    src: "{{ crc_tmp_dir }}/{{ crc_ocp_download_file_name }}"
    dest: /usr/local/bin
    remote_src: yes
    exclude:
      - "README.md"

- name: "{{ crc_mode }} | crc | ocp | check installed"
  become: true
  ansible.builtin.command: oc version
  register: __crc_ocp_install_status
  changed_when: __crc_ocp_install_status.rc == 0

- name: "{{ crc_mode }} | crc | kubectl | check installed"
  become: true
  ansible.builtin.command: kubectl version
  register: __crc_kubectl_install_status
  changed_when: __crc_kubectl_install_status.rc == 1
