---

- name: "{{ crc_mode }} | crc | libvirtd service"
  become: true
  when:
    - not ansible_check_mode
    - crc_state == 'present'
  ansible.builtin.systemd:
    name: libvirtd
    state: started
    enabled: true
  register: __crc_libvirtd_status
  changed_when: __crc_libvirtd_status.state != 'started'

- name: "{{ crc_mode }} | crc | copying over dnsmasq configuration"
  become: true
  when:
    - not ansible_check_mode
    - crc_state == 'present'
  ansible.builtin.copy:
    src: crc-nm-none.conf
    dest: /etc/NetworkManager/conf.d/crc-nm-none.conf
    owner: root
    group: root
    mode: '0644'

- name: "{{ crc_mode }} | crc | copying over dnsmasq configuration for crc"
  become: true
  when:
    - not ansible_check_mode
    - crc_state == 'present'
  ansible.builtin.copy:
    src: crc-dnsmasq.conf
    dest: /etc/NetworkManager/dnsmasq.d/crc-dnsmasq.conf
    owner: root
    group: root
    mode: '0644'

- name: "{{ crc_mode }} | crc | enable and start NetworkManager service"
  become: true
  when:
    - not ansible_check_mode
    - crc_state == 'present'
  ansible.builtin.systemd:
    name: NetworkManager
    state: restarted
    enabled: yes

- name: "{{ crc_mode }} | crc | enable and start dnsmasq service"
  become: true
  when:
    - not ansible_check_mode
    - crc_state == 'present'
  ansible.builtin.systemd:
    name: dnsmasq
    state: restarted
    enabled: yes

- name: "{{ crc_mode }} | crc | copying over pull-secret.txt"
  become: true
  when:
    - not ansible_check_mode
    - crc_state == 'present'
  ansible.builtin.copy:
    content: "{{ crc_pull_secret }}"
    dest:  "{{ crc_pull_secret_path }}"
    owner: "{{ crc_user_owner }}"
    group: "{{ crc_user_group }}"
    mode: 0666

#- name: "{{ crc_mode }} | crc | cleanup CodeReady Deployment"
#  become: true
#  become_user: "{{ crc_user_owner }}"
#  become_method: community.general.machinectl
#  become_exe: "sudo machinectl"
#  when:
#    - not ansible_check_mode
#    - crc_state == 'absent'
#  ansible.builtin.shell: |
#    set -o pipefail
#    $HOME/.local/bin/crc cleanup | tee /tmp/setup_status.log

- name: "{{ crc_mode }} | crc | setup CodeReady Deployment"
  become: true
  become_user: "{{ crc_user_owner }}"
  become_method: community.general.machinectl
  become_exe: "sudo machinectl"
  when:
    - not ansible_check_mode
    - crc_state == 'present'
  ansible.builtin.shell: |
    set -o pipefail
    $HOME/.local/bin/crc config set consent-telemetry yes | tee /tmp/setup_status.log
    $HOME/.local/bin/crc config set nameserver {{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }} | tee /tmp/setup_status.log
    $HOME/.local/bin/crc config set network-mode system | tee /tmp/setup_status.log
    $HOME/.local/bin/crc setup | tee /tmp/setup_status.log

- name: "{{ crc_mode }} | crc | start CodeReady Deployment"
  become: true
  become_user: "{{ crc_user_owner }}"
  become_method: community.general.machinectl
  become_exe: "sudo machinectl"
  when:
    - not ansible_check_mode
    - crc_state == 'present'
  ansible.builtin.shell: |
    set -o pipefail
    $HOME/.local/bin/crc start -c {{ crc_cpu }} -m {{ crc_memory }} -p {{ crc_pull_secret_path }} --log-level {{ crc_log_level }} | tee /tmp/install_status.log

- name: "{{ crc_mode }} | crc | delete CodeReady Deployment"
  become: true
  become_user: "{{ crc_user_owner }}"
  when:
    - not ansible_check_mode
    - crc_state == 'absent'
  ansible.builtin.shell: |
    set -o pipefail
    $HOME/.local/bin/crc delete | tee /tmp/delete_status.log
