---

- name: Uninstall (crc_mode fact)
  ansible.builtin.set_fact:
    crc_mode: "Uninstall"

- name: "{{ crc_mode }} | crc"
  ansible.builtin.include_tasks: crc.yml

- name: "{{ crc_mode }} | crc | directories"
  ansible.builtin.include_tasks: directories.yml

- name: "{{ crc_mode }} | crc | users"
  ansible.builtin.include_tasks: users.yml
