---

- name: "{{ crc_mode }} | create ~/.local/bin"
  become: true
  become_user: "{{ crc_user_owner }}"
  become_method: community.general.machinectl
  become_exe: "sudo machinectl"
  when:
    - not ansible_check_mode
    - crc_state == 'present'
  ansible.builtin.file:
    state: "{{ crc_directories_state }}"
    path: "$HOME/.local/bin"
    mode: "{{ crc_directories_mode }}"
    owner: "{{ crc_user_owner }}"
    group: "{{ crc_user_group }}"
