---

- name: "{{ crc_mode }} | users | get crc_user_owner_info"
  ansible.builtin.user:
    name: "{{ crc_user_owner }}"
  changed_when: false
  register: __crc_user_owner_info

- name: "{{ crc_mode }} | users | manage variable CRC_BIN_PATH in ~/.bashrc.d/crc_bin_path.rc"
  when: crc_state == 'present'
  become: true
  ansible.builtin.copy:
    dest: "{{ __crc_user_owner_info.home }}/.bashrc.d/crc_bin_path.rc"
    content: |
       export CRC_BIN_PATH={{ crc_bin_dir }}/crc
       export PATH=$PATH:$CRC_BIN_PATH
    owner: "{{ crc_user_owner }}"
    group: "{{ crc_user_group }}"
    mode: "{{ crc_files_mode }}"
