---

- name: "{{ crc_mode }} | users | manage variable CRC_BIN_PATH in ~/.bashrc.d/crc_bin_path.rc"
  when: crc_state == 'present'
  become: true
  become_user: "{{ crc_user_owner }}"
  become_method: community.general.machinectl
  become_exe: "sudo machinectl"
  ansible.builtin.copy:
    dest: $HOME/.bashrc.d/crc_bin_path.rc
    content: |
       export CRC_BIN_PATH={{ crc_bin_dir }}/crc
       export PATH=$PATH:$CRC_BIN_PATH
    owner: "{{ crc_user_owner }}"
    group: "{{ crc_user_group }}"
    mode: 0750
