---

- name: "{{ crc_mode }} | crc | users | get crc_user_owner_info"
  when: infra_state == 'present'
  ansible.builtin.user:
    name: "{{ crc_user_owner }}"
  check_mode: true
  changed_when: false
  register: __crc_user_owner_info

- name: "{{ crc_mode }} | crc | users | create folder ~/.bashrc.d/ to add some nice config"
  when:
    - not ansible_check_mode
    - crc_state == 'present'
  become: true
  ansible.builtin.file:
    path: "{{ __crc_user_owner_info.home }}/.bashrc.d"
    state: directory
    owner: "{{ crc_user_owner }}"
    group: "{{ crc_user_group }}"
    mode: 0755
